# Generated by Django 3.2.9 on 2021-11-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(blank=True, default='', max_length=100)),
                ('valid_till', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['units'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('School', models.CharField(blank=True, default='', max_length=100)),
                ('id_no', models.CharField(blank=True, default='', max_length=100)),
                ('Course', models.CharField(blank=True, default='', max_length=100)),
                ('valid_till', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(blank=True, default='', max_length=100)),
                ('School', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('duration', models.CharField(blank=True, default='', max_length=100)),
                ('Topic', models.CharField(blank=True, default='', max_length=100)),
                ('day_taught', models.CharField(blank=True, default='', max_length=100)),
                ('time_taught', models.CharField(blank=True, default='', max_length=100)),
                ('assignment', models.CharField(blank=True, default='', max_length=100)),
                ('valid_till', models.CharField(blank=True, default='', max_length=100)),
                ('assignment_till', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['unit_name'],
            },
        ),
    ]
