# Generated by Django 3.2.9 on 2021-11-27 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_unit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['day_taught']},
        ),
    ]
