# Generated by Django 3.2.9 on 2021-11-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_unit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['time_taught']},
        ),
    ]
