# Generated by Django 3.2.9 on 2021-11-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_unit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['unit_name']},
        ),
    ]
